# Generated by Django 5.0.4 on 2024-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=50)),
                ('contraseña', models.TextField(max_length=50)),
            ],
        ),
    ]
