# Generated by Django 5.0.4 on 2024-04-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_usuario_tipo_alumno_curso_alumno_curso_alumno_padre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='edadalum',
            new_name='edad_alum',
        ),
    ]
