# Generated by Django 5.0.4 on 2024-04-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_remove_curso_alumnos_curso_curso_alumnos_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='usuario_profe',
            new_name='usuario_alum',
        ),
        migrations.AlterField(
            model_name='curso',
            name='alumnos_curso',
            field=models.ManyToManyField(related_name='alumnos', to='colegio.alumno'),
        ),
    ]
