# Generated by Django 5.0.4 on 2024-04-26 03:10

from django.db import migrations


def asignar_curso_a_alumnos(apps, schema_editor):
    Alumno = apps.get_model('colegio', 'Alumno')
    Curso = apps.get_model('colegio', 'Curso')
    
    # Aquí puedes asignar un curso específico a todos los alumnos existentes
    curso_default = Curso.objects.first()  # O cualquier otra lógica para obtener el curso deseado
    
    for alumno in Alumno.objects.all():
        alumno.curso = curso_default
        alumno.save()

class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_rename_usuario_profe_alumno_usuario_alum_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_curso_a_alumnos),
    ]
