# Generated by Django 5.0.4 on 2024-04-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_auto_20240425_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre_alum',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre_curso',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='hijo',
            new_name='hijos',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='email_padre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='email_profe',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='curso_alumno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad_alum',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario_alum',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor_curso',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='edad_padre',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='nombre_padre',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='usuario_padre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='edad_profe',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre_profe',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuario_profe',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='colegio.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='colegio.profesor'),
        ),
        migrations.AddField(
            model_name='padre',
            name='edad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='padre',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='padre',
            name='usuario',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.usuario'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.usuario'),
        ),
    ]
